apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofa-registry-integration
  labels:
    app: sofa-registry
    type: integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sofa-registry
      type: integration
  template:
    metadata:
      labels:
        app: sofa-registry
        type: integration
    spec:
      containers:
        - name: sofa-registry
          image: dzdx/sofa-registry-test:latest
          env:
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sofa-registry-integration-secret
                  key: JDBC_PASSWORD
            - name: REGISTRY_APP_NAME
              value: integration
          volumeMounts:
            - name: config-volume
              mountPath: /registry-distribution/registry-all/conf
      volumes:
        - name: config-volume
          configMap:
            name: sofa-registry-integration-config
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sofa-registry-integration-config
data:
  application.properties: |
    nodes.localDataCenter=DefaultDataCenter
    nodes.localRegion=DEFAULT_ZONE
    jdbc.url=jdbc:mysql://mysql.default.svc.cluster.local:3306/registrymetadb
    jdbc.username=root
    jdbc.password=
---
apiVersion: v1
kind: Secret
metadata:
  name: sofa-registry-integration-secret
type: Opaque
stringData:
  JDBC_PASSWORD: root