// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentMetadataPb.proto

package com.alipay.sofa.registry.common.model.client.pb;

public interface SegmentMetadataPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SegmentMetadataPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool localSegment = 1;</code>
   * @return The localSegment.
   */
  boolean getLocalSegment();

  /**
   * <code>string segment = 2;</code>
   * @return The segment.
   */
  java.lang.String getSegment();
  /**
   * <code>string segment = 2;</code>
   * @return The bytes for segment.
   */
  com.google.protobuf.ByteString
      getSegmentBytes();

  /**
   * <code>repeated string zones = 3;</code>
   * @return A list containing the zones.
   */
  java.util.List<java.lang.String>
      getZonesList();
  /**
   * <code>repeated string zones = 3;</code>
   * @return The count of zones.
   */
  int getZonesCount();
  /**
   * <code>repeated string zones = 3;</code>
   * @param index The index of the element to return.
   * @return The zones at the given index.
   */
  java.lang.String getZones(int index);
  /**
   * <code>repeated string zones = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the zones at the given index.
   */
  com.google.protobuf.ByteString
      getZonesBytes(int index);
}
