// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentMetadataPb.proto

package com.alipay.sofa.registry.common.model.client.pb;

/**
 * Protobuf type {@code SegmentMetadataPb}
 */
public final class SegmentMetadataPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SegmentMetadataPb)
    SegmentMetadataPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SegmentMetadataPb.newBuilder() to construct.
  private SegmentMetadataPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentMetadataPb() {
    localSegmentZones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SegmentMetadataPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SegmentMetadataPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            localSegment_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              localSegmentZones_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            localSegmentZones_.add(s);
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              data_ = com.google.protobuf.MapField.newMapField(
                  DataDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
            data__ = input.readMessage(
                DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            data_.getMutableMap().put(
                data__.getKey(), data__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        localSegmentZones_ = localSegmentZones_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPbOuterClass.internal_static_SegmentMetadataPb_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPbOuterClass.internal_static_SegmentMetadataPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb.class, com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb.Builder.class);
  }

  public static final int LOCALSEGMENT_FIELD_NUMBER = 1;
  private boolean localSegment_;
  /**
   * <code>bool localSegment = 1;</code>
   * @return The localSegment.
   */
  @java.lang.Override
  public boolean getLocalSegment() {
    return localSegment_;
  }

  public static final int LOCALSEGMENTZONES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList localSegmentZones_;
  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @return A list containing the localSegmentZones.
   */
  public com.google.protobuf.ProtocolStringList
      getLocalSegmentZonesList() {
    return localSegmentZones_;
  }
  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @return The count of localSegmentZones.
   */
  public int getLocalSegmentZonesCount() {
    return localSegmentZones_.size();
  }
  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @param index The index of the element to return.
   * @return The localSegmentZones at the given index.
   */
  public java.lang.String getLocalSegmentZones(int index) {
    return localSegmentZones_.get(index);
  }
  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the localSegmentZones at the given index.
   */
  public com.google.protobuf.ByteString
      getLocalSegmentZonesBytes(int index) {
    return localSegmentZones_.getByteString(index);
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private static final class DataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>newDefaultInstance(
                com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPbOuterClass.internal_static_SegmentMetadataPb_DataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.alipay.sofa.registry.common.model.client.pb.StringList.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> data_;
  private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
  internalGetData() {
    if (data_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DataDefaultEntryHolder.defaultEntry);
    }
    return data_;
  }

  public int getDataCount() {
    return internalGetData().getMap().size();
  }
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */

  @java.lang.Override
  public boolean containsData(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> getData() {
    return getDataMap();
  }
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> getDataMap() {
    return internalGetData().getMap();
  }
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */
  @java.lang.Override

  public com.alipay.sofa.registry.common.model.client.pb.StringList getDataOrDefault(
      java.lang.String key,
      com.alipay.sofa.registry.common.model.client.pb.StringList defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> map =
        internalGetData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */
  @java.lang.Override

  public com.alipay.sofa.registry.common.model.client.pb.StringList getDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> map =
        internalGetData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (localSegment_ != false) {
      output.writeBool(1, localSegment_);
    }
    for (int i = 0; i < localSegmentZones_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, localSegmentZones_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetData(),
        DataDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (localSegment_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, localSegment_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < localSegmentZones_.size(); i++) {
        dataSize += computeStringSizeNoTag(localSegmentZones_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLocalSegmentZonesList().size();
    }
    for (java.util.Map.Entry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> entry
         : internalGetData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
      data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, data__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb)) {
      return super.equals(obj);
    }
    com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb other = (com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb) obj;

    if (getLocalSegment()
        != other.getLocalSegment()) return false;
    if (!getLocalSegmentZonesList()
        .equals(other.getLocalSegmentZonesList())) return false;
    if (!internalGetData().equals(
        other.internalGetData())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCALSEGMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLocalSegment());
    if (getLocalSegmentZonesCount() > 0) {
      hash = (37 * hash) + LOCALSEGMENTZONES_FIELD_NUMBER;
      hash = (53 * hash) + getLocalSegmentZonesList().hashCode();
    }
    if (!internalGetData().getMap().isEmpty()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SegmentMetadataPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SegmentMetadataPb)
      com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPbOuterClass.internal_static_SegmentMetadataPb_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPbOuterClass.internal_static_SegmentMetadataPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb.class, com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb.Builder.class);
    }

    // Construct using com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      localSegment_ = false;

      localSegmentZones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableData().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPbOuterClass.internal_static_SegmentMetadataPb_descriptor;
    }

    @java.lang.Override
    public com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb getDefaultInstanceForType() {
      return com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb build() {
      com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb buildPartial() {
      com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb result = new com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb(this);
      int from_bitField0_ = bitField0_;
      result.localSegment_ = localSegment_;
      if (((bitField0_ & 0x00000001) != 0)) {
        localSegmentZones_ = localSegmentZones_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.localSegmentZones_ = localSegmentZones_;
      result.data_ = internalGetData();
      result.data_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb) {
        return mergeFrom((com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb other) {
      if (other == com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb.getDefaultInstance()) return this;
      if (other.getLocalSegment() != false) {
        setLocalSegment(other.getLocalSegment());
      }
      if (!other.localSegmentZones_.isEmpty()) {
        if (localSegmentZones_.isEmpty()) {
          localSegmentZones_ = other.localSegmentZones_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureLocalSegmentZonesIsMutable();
          localSegmentZones_.addAll(other.localSegmentZones_);
        }
        onChanged();
      }
      internalGetMutableData().mergeFrom(
          other.internalGetData());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean localSegment_ ;
    /**
     * <code>bool localSegment = 1;</code>
     * @return The localSegment.
     */
    @java.lang.Override
    public boolean getLocalSegment() {
      return localSegment_;
    }
    /**
     * <code>bool localSegment = 1;</code>
     * @param value The localSegment to set.
     * @return This builder for chaining.
     */
    public Builder setLocalSegment(boolean value) {
      
      localSegment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool localSegment = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalSegment() {
      
      localSegment_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList localSegmentZones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLocalSegmentZonesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        localSegmentZones_ = new com.google.protobuf.LazyStringArrayList(localSegmentZones_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @return A list containing the localSegmentZones.
     */
    public com.google.protobuf.ProtocolStringList
        getLocalSegmentZonesList() {
      return localSegmentZones_.getUnmodifiableView();
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @return The count of localSegmentZones.
     */
    public int getLocalSegmentZonesCount() {
      return localSegmentZones_.size();
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @param index The index of the element to return.
     * @return The localSegmentZones at the given index.
     */
    public java.lang.String getLocalSegmentZones(int index) {
      return localSegmentZones_.get(index);
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the localSegmentZones at the given index.
     */
    public com.google.protobuf.ByteString
        getLocalSegmentZonesBytes(int index) {
      return localSegmentZones_.getByteString(index);
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @param index The index to set the value at.
     * @param value The localSegmentZones to set.
     * @return This builder for chaining.
     */
    public Builder setLocalSegmentZones(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLocalSegmentZonesIsMutable();
      localSegmentZones_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @param value The localSegmentZones to add.
     * @return This builder for chaining.
     */
    public Builder addLocalSegmentZones(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLocalSegmentZonesIsMutable();
      localSegmentZones_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @param values The localSegmentZones to add.
     * @return This builder for chaining.
     */
    public Builder addAllLocalSegmentZones(
        java.lang.Iterable<java.lang.String> values) {
      ensureLocalSegmentZonesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, localSegmentZones_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalSegmentZones() {
      localSegmentZones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string localSegmentZones = 2;</code>
     * @param value The bytes of the localSegmentZones to add.
     * @return This builder for chaining.
     */
    public Builder addLocalSegmentZonesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureLocalSegmentZonesIsMutable();
      localSegmentZones_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> data_;
    private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
    internalGetMutableData() {
      onChanged();;
      if (data_ == null) {
        data_ = com.google.protobuf.MapField.newMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      if (!data_.isMutable()) {
        data_ = data_.copy();
      }
      return data_;
    }

    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, .StringList&gt; data = 3;</code>
     */

    @java.lang.Override
    public boolean containsData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, .StringList&gt; data = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, .StringList&gt; data = 3;</code>
     */
    @java.lang.Override

    public com.alipay.sofa.registry.common.model.client.pb.StringList getDataOrDefault(
        java.lang.String key,
        com.alipay.sofa.registry.common.model.client.pb.StringList defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .StringList&gt; data = 3;</code>
     */
    @java.lang.Override

    public com.alipay.sofa.registry.common.model.client.pb.StringList getDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearData() {
      internalGetMutableData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .StringList&gt; data = 3;</code>
     */

    public Builder removeData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
    getMutableData() {
      return internalGetMutableData().getMutableMap();
    }
    /**
     * <code>map&lt;string, .StringList&gt; data = 3;</code>
     */
    public Builder putData(
        java.lang.String key,
        com.alipay.sofa.registry.common.model.client.pb.StringList value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableData().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .StringList&gt; data = 3;</code>
     */

    public Builder putAllData(
        java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList> values) {
      internalGetMutableData().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SegmentMetadataPb)
  }

  // @@protoc_insertion_point(class_scope:SegmentMetadataPb)
  private static final com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb();
  }

  public static com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SegmentMetadataPb>
      PARSER = new com.google.protobuf.AbstractParser<SegmentMetadataPb>() {
    @java.lang.Override
    public SegmentMetadataPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SegmentMetadataPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SegmentMetadataPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentMetadataPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alipay.sofa.registry.common.model.client.pb.SegmentMetadataPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

