// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentMetadataPb.proto

package com.alipay.sofa.registry.common.model.client.pb;

public final class SegmentMetadataPbOuterClass {
  private SegmentMetadataPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SegmentMetadataPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SegmentMetadataPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027SegmentMetadataPb.proto\"I\n\021SegmentMeta" +
      "dataPb\022\024\n\014localSegment\030\001 \001(\010\022\017\n\007segment\030" +
      "\002 \001(\t\022\r\n\005zones\030\003 \003(\tB:\n/com.alipay.sofa." +
      "registry.common.model.client.pbP\001Z\005proto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SegmentMetadataPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SegmentMetadataPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SegmentMetadataPb_descriptor,
        new java.lang.String[] { "LocalSegment", "Segment", "Zones", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
