// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentMetadataPb.proto

package com.alipay.sofa.registry.common.model.client.pb;

public interface SegmentMetadataPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SegmentMetadataPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool localSegment = 1;</code>
   * @return The localSegment.
   */
  boolean getLocalSegment();

  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @return A list containing the localSegmentZones.
   */
  java.util.List<java.lang.String>
      getLocalSegmentZonesList();
  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @return The count of localSegmentZones.
   */
  int getLocalSegmentZonesCount();
  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @param index The index of the element to return.
   * @return The localSegmentZones at the given index.
   */
  java.lang.String getLocalSegmentZones(int index);
  /**
   * <code>repeated string localSegmentZones = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the localSegmentZones at the given index.
   */
  com.google.protobuf.ByteString
      getLocalSegmentZonesBytes(int index);

  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
  getData();
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */
  java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.StringList>
  getDataMap();
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */

  com.alipay.sofa.registry.common.model.client.pb.StringList getDataOrDefault(
      java.lang.String key,
      com.alipay.sofa.registry.common.model.client.pb.StringList defaultValue);
  /**
   * <code>map&lt;string, .StringList&gt; data = 3;</code>
   */

  com.alipay.sofa.registry.common.model.client.pb.StringList getDataOrThrow(
      java.lang.String key);
}
